name: Deploy to GitHub Pages

on:
  push:
    branches: 'dev' # or whichever branch you want to deploy from

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: '--max-old-space-size=8192' # Increase memory limit for Node.js
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: build
        env:
          BASE_PATH: '/${{ github.event.repository.name }}'
          ## Add and uncomment any environment variables here
          EVIDENCE_SOURCE__ANC__FILENAME: ${{ secrets.EVIDENCE_SOURCE__ANC__FILENAME }}
          EVIDENCE_SOURCE__CRASHES__FILENAME: ${{ secrets.EVIDENCE_SOURCE__CRASHES__FILENAME }}
          EVIDENCE_SOURCE__DC_BOUNDARY__FILENAME: ${{ secrets.EVIDENCE_SOURCE__DC_BOUNDARY__FILENAME }}
          EVIDENCE_SOURCE__HEXGRID__FILENAME: ${{ secrets.EVIDENCE_SOURCE__HEXGRID__FILENAME }}
          EVIDENCE_SOURCE__HIN__FILENAME: ${{ secrets.EVIDENCE_SOURCE__HIN__FILENAME }}
          EVIDENCE_SOURCE__INTERSECTIONS__FILENAME: ${{ secrets.EVIDENCE_SOURCE__INTERSECTIONS__FILENAME }}
          EVIDENCE_SOURCE__SMD__FILENAME: ${{ secrets.EVIDENCE_SOURCE__SMD__FILENAME }}
          EVIDENCE_SOURCE__WARDS__FILENAME: ${{ secrets.EVIDENCE_SOURCE__WARDS__FILENAME }}
        run: |
          npm run sources
          npm run build

      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'build/${{ github.event.repository.name }}'

  deploy:
    needs: build
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4