name: Deploy Clean Version to Org Repo

on:
  push:
    branches:
      - dev  # adjust if you need a different branch
  # Optional: manual trigger
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the full repository history
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Step 2: Create an archive, remove unwanted files, and modify files
      - name: Prepare Clean Archive
        run: |
          # Create a temporary directory for the deployable version
          mkdir deploy
          # Export the repository content into the "deploy" folder
          git archive HEAD | tar -x -C deploy
          
          # Edit the files in /pages to update the links

          # Update /pages/hexgrid/index.md:
          sed -i "s|'/hexgrid/' || h.GRID_ID AS link|'/Crash-Injury-Dashboard-Frontend/hexgrid/' || h.GRID_ID AS link|g" deploy/pages/hexgrid/index.md
          
          # Update /pages/anc/index.md:
          sed -i "s|'/anc/' || a.ANC AS link|'/Crash-Injury-Dashboard-Frontend/anc/' || a.ANC AS link|g" deploy/pages/anc/index.md
          
          # Update /pages/smd/index.md:
          sed -i "s|'/smd/' || a.SMD AS link|'/Crash-Injury-Dashboard-Frontend/smd/' || a.SMD AS link|g" deploy/pages/smd/index.md

      # Step 3: Initialize a new Git repository in the deploy folder
      - name: Initialize Clean Repo for Deployment
        working-directory: deploy
        run: |
          git init
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Deploying clean version to organization repository"

      # Step 4: Push the clean version to the organization repository
      - name: Push Clean Version to Org Repository
        working-directory: deploy
        env:
          ORG_TOKEN: ${{ secrets.ORG_TOKEN }}
        run: |
          # Add the organization repository as a remote destination.
          # The URL includes your username and the PAT stored as secret.
          git remote add origin https://rafaelmorenoco:${ORG_TOKEN}@github.com/dcvisionzero/Crash-Injury-Dashboard-Frontend.git
          # Force push the clean commit to the desired branch (e.g., master)
          git push origin master --force
