name: Merge dev to main (Exclude Workflows)

on:
  workflow_dispatch:
  repository_dispatch:
    types: [update-crashes]

permissions:
  contents: write

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      # 1. Check out the main branch with full history.
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0

      # 2. Configure Git.
      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      # 3. Merge dev into main (excluding changes in .github/workflows).
      - name: Merge dev into main excluding workflows
        run: |
          # Fetch the latest dev branch.
          git fetch origin dev
          # Merge origin/dev into main without auto-committing.
          git merge origin/dev --no-commit --no-ff || true
          
          # Remove any changes in the .github/workflows folder made by the merge.
          rm -rf .github/workflows
          # Restore the entire workflows folder from origin/main.
          git checkout origin/main -- .github/workflows
          git add .github/workflows
          
          # Resolve crashes.parquet conflicts by taking the version from dev.
          git checkout --theirs crashes.parquet || true
          git add crashes.parquet
          
          # If any changes are staged, commit them.
          if ! git diff --cached --quiet; then
            git commit -m "Merge dev into main excluding workflows (skip CI)"
          else
            echo "No merge commit necessary; nothing to commit."
          fi

      # 4. Push the merge commit to main.
      - name: Push changes
        run: |
          git push origin main